### ISSUE TITLE
wrong pin-numbering in attiny-code for pulse-version

### ISSUE THREAD

**Issue by l0j0** [robert-hh/ATTiny-Watchdog-for-MicroPython#1]
it seems the pin numbers in the pulse-version of the attiny code (watchdog.ino) are exchanged:
it reads: 
#define FEED_PIN 3
#define DEBUG_PIN 2
#define STATUS_PIN 1
#define RESET_PIN 4

but should be (also according readme and kicad schema):
#define FEED_PIN 4
#define DEBUG_PIN 2
#define STATUS_PIN 1
#define RESET_PIN 3

thanks for this great project btw!

**Comment by robert-hh** [comment]
Thank you for the note. It may be, that I changed the pin assignment for an easier Board layout. I'll change that.

**Comment by robert-hh** [comment]
Changed. And thank you very much for the hint.
